version: '3.8'

services:
  blobberman:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    command:
      - "--addr=:8080"
      - "--static-dir=./public"
      - "--tick-interval=50"
      - "--verbose=true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
